### ISSUE TITLE
Error on start application with firebase

### ISSUE THREAD

**Issue by filipecaires** [asyrafduyshart/antd-firebase-dashboard#5]
On start application with firebase, the error next return in terminal.

./node_modules/history/esm/history.js
Module not found: Can't resolve '@babel/runtime/helpers/esm/extends' in '/Users/filipecaires/DEVDREAMS/WEB/antd-firebase-dashboard-master/node_modules/history/esm'

I`m executed command npm audit fix, but the error continue.

**Comment by asyrafduyshart** [comment]
check newest version 2
